CREATE DATABASE IF NOT EXISTS `chirpDB` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `board` (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CREATED_AT TIMESTAMP(6),

    NAME VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE `site_user` (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CREATED_AT TIMESTAMP(6),

    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(255) UNIQUE NOT NULL,
    ROLE VARCHAR(32) DEFAULT 'USER'
);
