CREATE DATABASE IF NOT EXISTS `chirpDB` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `board` (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CREATED_AT TIMESTAMP(6),

    NAME VARCHAR(32) UNIQUE NOT NULL,

    INDEX idx_name (NAME)
);

CREATE TABLE `site_user` (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CREATED_AT TIMESTAMP(6),

    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(255) UNIQUE NOT NULL,
    ROLE VARCHAR(32) DEFAULT 'USER',

    INDEX idx_email (EMAIL)
);

CREATE TABLE `article` (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CREATED_AT TIMESTAMP(6),

    TITLE VARCHAR(255),
    CONTENT VARCHAR(255),
    BOARD_ID BIGINT NOT NULL,
    WRITER_ID BIGINT NOT NULL,
    VIEWS BIGINT DEFAULT 0,

    INDEX idx_board_id (BOARD_ID)
);

CREATE TABLE `article_comment` (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CREATED_AT TIMESTAMP(6),

    CONTENT VARCHAR(255),
    ARTICLE_ID BIGINT NOT NULL,
    WRITER_ID BIGINT NOT NULL,

    INDEX idx_article_id (ARTICLE_ID)
);

CREATE TABLE `article_likes` (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CREATED_AT TIMESTAMP(6),

    ARG TINYINT,
    ARTICLE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,

    INDEX idx_article_id_user_id (ARTICLE_ID, USER_ID)
);

CREATE TABLE `article_comment_likes` (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CREATED_AT TIMESTAMP(6),

    ARG TINYINT,
    ARTICLE_COMMENT_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,

    INDEX idx_article_id_user_id (ARTICLE_COMMENT_ID, USER_ID)
);

ALTER TABLE `article`
ADD CONSTRAINT fk_article_board
FOREIGN KEY (BOARD_ID) REFERENCES `board`(ID)
ON DELETE CASCADE;

ALTER TABLE `article`
ADD CONSTRAINT fk_article_writer
FOREIGN KEY (WRITER_ID) REFERENCES `site_user`(ID)
ON DELETE CASCADE;

ALTER TABLE `article_comment`
ADD CONSTRAINT fk_comment_article
FOREIGN KEY (ARTICLE_ID) REFERENCES `article`(ID)
ON DELETE CASCADE;

ALTER TABLE `article_comment`
ADD CONSTRAINT fk_comment_writer
FOREIGN KEY (WRITER_ID) REFERENCES `site_user`(ID);

ALTER TABLE `article_likes`
ADD CONSTRAINT fk_article_likes_article
FOREIGN KEY (ARTICLE_ID) REFERENCES `article`(ID)
ON DELETE CASCADE;

ALTER TABLE `article_likes`
ADD CONSTRAINT fk_article_likes_user
FOREIGN KEY (USER_ID) REFERENCES `site_user`(ID);

ALTER TABLE `article_comment_likes`
ADD CONSTRAINT fk_comment_likes_comment
FOREIGN KEY (ARTICLE_COMMENT_ID) REFERENCES `article_comment`(ID)
ON DELETE CASCADE;

ALTER TABLE `article_comment_likes`
ADD CONSTRAINT fk_comment_likes_user
FOREIGN KEY (USER_ID) REFERENCES `site_user`(ID);
